### ISSUE TITLE
get_ohlcv 호출 시 None type이 리턴되는 경우

### ISSUE THREAD

**Issue by greatman91** [sharebook-kr/pyupbit#1]
안녕하십니까, 개발하신 pyupbit 잘 사용하고 있는 초보 개발자입니다.
다름이 아니라 5초마다 get_ohlcv를 호출하고 있는데 잘 되다가 가끔 None 타입을 반환하는 경우가 있는데 이 경우는 업비트 서버에 문제가 있어서 그런 것인지 아니면 세션 연결 과정에서 어떤 문제가 있어서 그런 것인지 궁금합니다.
감사합니다.

**Comment by captinh** [comment]
해결하였습니다. 감사합니다.
