### ISSUE TITLE
get_ohlcv에서 to 파라미터 사용 건의

### ISSUE THREAD

**Issue by hammermill** [sharebook-kr/pyupbit#10]
안녕하십니까, pyupbit를 아주 잘 사용하고 있는 왕초보 개발자입니다.

pyupbit로 백테스팅을 하려고 하는데요 get_ohlcv는 최근 200개만 가져올수 있어서 백테스팅을 하기에는 데이터가 모자랍니다.
최근 200개가 아니라 그 전 data도 사용할 수 있게 to 파라미터를 이용해서 특정 기간까지 가져올 수 있게 해주시면 좋을 것 같습니다.

**Comment by brayden-jo** [comment]
네. 맞습니다. 제가 api를 잘못 이해해서 처음에 그렇게 만들었습니다. 반영하겠습니다.

**Comment by brayden-jo** [comment]
반영했습니다.
