### ISSUE TITLE
buy_market_order is giving UnderMinTotalBid error?

### ISSUE THREAD

**Issue by StockSenz** [sharebook-kr/pyupbit#121]
I am sending the market order request as follows - 

market_id = "KRW-ARB"
orderbook = pyupbit.get_orderbook(market_id)
`_price = orderbook['orderbook_units'][0]['ask_price']`
`order = upbit.buy_market_order(market_id, _price)`

The error i am getting is this UnderMinTotalBid. 
Can you please explain it how?

**Comment by pick8chu** [comment]
https://docs.upbit.com/docs/api-%EC%A3%BC%EC%9A%94-%EC%97%90%EB%9F%AC-%EC%BD%94%EB%93%9C-%EB%AA%A9%EB%A1%9D#400-bad-request

<img width="594" alt="image" src="https://github.com/sharebook-kr/pyupbit/assets/47326528/90e0ba54-c2ed-4f82-8339-b515e0517713">

**Comment by mr-yoo** [comment]
thank you, pick8chu.
