### ISSUE TITLE
get_current_price 궁금한게 있습니다. 

### ISSUE THREAD

**Issue by hyeonjune-maker** [sharebook-kr/pyupbit#13]
```
tickers= pyupbit.get_tickers(fiat="KRW")
current_prices = pyupbit.get_current_price(tickers)

print(len(tickers))                #113
print(len(current_prices))         #100
```

113개의 데이터셋의 현재가를 보려고 하면 100개만 조회가 됩니다. 
이유가 무엇인지 궁금합니다.

**Comment by brayden-jo** [comment]
api 자체에서 한 번에 최대 100까지만 조회가가능한듯 합니다. 

`
tickers = pyupbit.get_tickers(fiat="KRW")
tickers1 = tickers[:100]
tickers2 = tickers[100:]
`

위와 같이 100개 단위로 나눠서 호출해야할듯 합니다.
