### ISSUE TITLE
공지사항이나 공시를 가져오는 기능 추가 여부

### ISSUE THREAD

**Issue by pimelode** [sharebook-kr/pyupbit#16]
공식 api에서 제공하지 않는 기능인데

공지사항이나 프로젝트 공시를 가져오는 기능을

추가해주실 수 없나요?

**Comment by susemeee** [comment]
공식 API에 없는 기능은 보통 웹 크롤링이나 private API를 따서 정보를 가져올 수 있는데, 업비트 웹의 경우에는 CloudFlare 보호 기능이 걸려있어 selenium 등을 사용하지 않으면 크롤링이 매우 힘듭니다.

그래서 API 분석 후 웹 클라이언트와 동일한 형태로 호출하는 방식으로 정보를 가져왔는데, 공지도 비슷한 방법으로 하면 되지 않을까 싶네요. (저는 코인별 출금 수수료를 비슷한 방법으로 가져왔습니다)

**Comment by Codejune** [comment]
현재 업비트 측에서 공시정보에 대한 정보 전달을 중지하였으며, api상에서 제공하지 않는 상황입니다. 이에따라 필요하실 경우 직접 파싱을 시도하시는 것이 좋을 것 같습니다
