### ISSUE TITLE
pyupbit.get_daily_ohlcv_from_base(ticker, base=0)가 10일어치 캔들만 반환합니다.

### ISSUE THREAD

**Issue by elementarya** [sharebook-kr/pyupbit#17]
get_ohlcv는 9시로 고정되어있어 pyupbit.get_daily_ohlcv_from_base(ticker, base=0)로 기준시간을 바꿔서 쓰려 했는데 
10일어치만 반환합니다. 
interval을 넣어봤는데 이 역시 작동하지 않습니다.

    pll=pyupbit.get_daily_ohlcv_from_base("KRW-BTC", interval="minute1", to=20210318)
TypeError: get_daily_ohlcv_from_base() got an unexpected keyword argument 'interval'

**Comment by ikkino1** [comment]
저도 비슷한 문제를 경험하고 있습니다. interval은 잘 작동하는데요, count를 어떻게 넣어도 항상 200개만 반환이 되네요. 어떻게 해야될까요?

**Comment by Codejune** [comment]
해당 함수의 경우 get_ohclv
