### ISSUE TITLE
시장가 매수/매도 함수 수정 요청

### ISSUE THREAD

**Issue by tyolee** [sharebook-kr/pyupbit#2]
시장가 매수/매도 기능을 업비트에서 제공하지 않아 자체적으로 구현하셨는데

함수를 그대로 사용했더니 몇번 급등시 시장가 매수를 하지 못한 상황이 있었습니다.

그래서 upbit api guide를 보니 order_type에 limit이 아니라 price, market을 주면 시장가 매수/매도를 할 수 있게끔 제공이 되더라구요...

이 기능을 사용해서 재구현 되어야 할 것 같습니다.

제가 임시로 사용중인 함수 공유합니다. (기존 함수에서 변수만 수정)

    def yklee_buy_market_order(self, ticker, price):
        '''
        지정가 매수
        :param ticker: 마켓 티커
        :param price: 주문 가격
        :return:
        '''
        try:
            url = "https://api.upbit.com/v1/orders"
            data = {"market": ticker,
                    "side": "bid",
                    "price": str(price),
                    "ord_type": "price"}
            headers = self._request_headers(data)
            return _send_post_request(url, headers=headers, data=data)
        except Exception as x:
            print(x.__class__.__name__)
            return None

    def yklee_sell_market_order(self, ticker, volume):
        '''
        지정가 매도
        :param ticker: 마켓 티커
        :param price: 주문 가격
        :param volume: 주문 수량
        :return:
        '''
        try:
            url = "https://api.upbit.com/v1/orders"
            data = {"market": ticker,
                    "side": "ask",
                    "volume": str(volume),
                    "ord_type": "market"}
            headers = self._request_headers(data)
            return _send_post_request(url, headers=headers, data=data)
        except Exception as x:
            print(x.__class__.__name__)
            return None

**Comment by sharebook-kr** [comment]
늦었지만 반영했습니다.
