### ISSUE TITLE
더 나은 예외처리 방법 제안

### ISSUE THREAD

**Issue by susemeee** [sharebook-kr/pyupbit#23]
지금 코드에서는 request 후 예외 발생시 print만 해준 후 None을 반환하고 있습니다.

라이브러리를 활용할 때 None을 받는것보다 몇 개의 custom exception을 정의한 후 exception이 발생하는 상황에 따라 해당 exception들을 raise하는 편이 사용하는 입장에서 조금 더 명확하지 않을까 싶네요.

이를 바로 업데이트하는 경우 하위호환성이 깨질 수 있을 것 같아 일단 이슈로만 남겨두겠습니다.

**Comment by brayden-jo** [comment]
좋은 의견 감사합니다.
