### ISSUE TITLE
평단가 확인 api 여부

### ISSUE THREAD

**Issue by hsm0711** [sharebook-kr/pyupbit#29]
안녕하세요 
pyupbit라이브러리를 잘 사용하고 있습니다.
혹시 평단가 조회 api 추가계획이 있으신지 문의드립니다.

**Comment by Codejune** [comment]
pyupbit 모듈에서 exchange api에서 보시면 get_balances 함수를 통해 보유중인 자산(코인)의 리스트를 rest요청을 통한 응답으로 제공합니다. 또한 각 항목에는 아래와 같은 형식으로 구매 평균 단가를 포함하여 정보를 제공합니다.

```json
[
  {
    "currency":"KRW",
    "balance":"1000000.0",
    "locked":"0.0",
    "avg_buy_price":"0",
    "avg_buy_price_modified":false,
    "unit_currency": "KRW",
  },
  {
    "currency":"BTC",
    "balance":"2.0",
    "locked":"0.0",
    "avg_buy_price":"101000",
    "avg_buy_price_modified":false,
    "unit_currency": "KRW",
  }
]
```
참고: https://docs.upbit.com/reference#%EC%9E%90%EC%82%B0-%EC%A1%B0%ED%9A%8C

**Comment by hsm0711** [comment]
/v1/orders/chance 해당 request에만 평단가 조회가있는줄 알았었네요.
답변 감사드립니다!
