### ISSUE TITLE
.get_ohlcv() 함수 minute1 일때 count 200을 초과 하면 중복열을 불러옴

### ISSUE THREAD

**Issue by lunaB** [sharebook-kr/pyupbit#30]
### 5분 1000개
![image](https://user-images.githubusercontent.com/23505078/117534576-f3302380-b02c-11eb-870f-1989a3a6147e.png)
### 1분 1000개
![image](https://user-images.githubusercontent.com/23505078/117534608-296da300-b02d-11eb-8042-06c851be201e.png)

확인해본 결과 1분만 잘 안되는것 같습니다.

**Comment by koreaplayer99** [comment]
Timezone을 utc로 바꾸고 다시 안돌아와서 그런 것 같습니다.
저는 임시로 9시간을 빼보니 정상작동합니다.

def get_ohlcv(ticker="KRW-BTC", interval="day", count=200, to=None, period=0.1):
    """
    캔들 조회
    :return:
    """
    MAX_CALL_COUNT = 200
    try:
        url = get_url_ohlcv(interval=interval)

        if to == None:
            to = datetime.datetime.now()
        elif isinstance(to, str):
            to = pd.to_datetime(to).to_pydatetime()
        elif isinstance(to, pd._libs.tslibs.timestamps.Timestamp):
            to = to.to_pydatetime()

        dfs = []
        count = max(count, 1)
        for pos in range(count, 0, -200):
            query_count = min(MAX_CALL_COUNT, pos)

            if to.tzinfo is None:
                to = to.astimezone()
            to = to.astimezone(datetime.timezone.utc)
            to = to.strftime("%Y-%m-%d %H:%M:%S")

            contents = _call_public_api(url, market=ticker, count=query_count, to=to)[0]
            dt_list = [datetime.datetime.strptime(x['candle_date_time_kst'], "%Y-%m-%dT%H:%M:%S") for x in contents]
            df = pd.DataFrame(contents, columns=['opening_price', 'high_price', 'low_price', 'trade_price',
                                                'candle_acc_trade_volume', 'candle_acc_trade_price'],
                            index=dt_list)
            df = df.sort_index()
            if df.shape[0] == 0:
                break
            dfs += [df]

            to = df.index[0].to_pydatetime()
            to = to - datetime.timedelta(hours=9)
            if pos > 200:
                time.sleep(period)

        df = pd.concat(dfs).sort_index()
        df = df.rename(
            columns={"opening_price": "open", "high_price": "high", "low_price": "low", "trade_price": "close",
                     "candle_acc_trade_volume": "volume", "candle_acc_trade_price": "value"})
        return df
    except Exception as x:
        print(x.__class__.__name__)
        return None

**Comment by mr-yoo** [comment]
이제야 답변을 다네요. 
@persona-twotwo 작성한 코드는 코랩에서는 정상 동작하지만 윈도우 개인 PC에서는 잘못된 결과가 나올 "수" 있습니다. 

----

웹서버가 반환한 결과(`contents`)에는 `kst`와 `utc`가 모두 들어 있습니다. 이 중에서 `kst`를 데이터프레임의 인덱스로 사용해서 보기 좋게 한국 시간으로 값을 출력합니다. 서버로 데이터를 요청할 때는 `utc`를 사용해야 합니다. 직접 계산하는 것 보다는 서버에서 전달해준 값을 사용하는게 안전(?)하기 때문에 다음과 같이 코드를 수정합니다. 

`to = datetime.datetime.strptime(contents[-1]['candle_date_time_utc'], "%Y-%m-%dT%H:%M:%S")`

다음 커밋에 위 내용을 업데이트했습니다. 
https://github.com/sharebook-kr/pyupbit/commit/266d576a247e80fc8e3427f58cc0abbb2305db1e
----

물론 kst를 utc로 계산해서 변경할 수도 있습니다. 코드를 실행하는 local 환경의 보정을 위해 `time.timezone + 32400` 코드가 사용됐습니다. 
- 코랩은 로컬이 'utc' 환경이라서 `timezone` 값이 0입니다. 
- 일반적인 윈도우 환경에서는 `timezone`이 -32400입니다. 

`to = df.index[0].to_pydatetime() - datetime.timedelta(seconds=time.timezone + 32400)`

**Comment by mr-yoo** [comment]
모듈 업데이트부터 해주세요
`!pip install -U pyupbit`

다음 코드를 실행하면 중복없이 총 1000개의 값을 확인할 수 잇씁니다. 
```python
import pyupbit

df = pyupbit.get_ohlcv('KRW-XRP', interval='minute5', count=1000)
print(len(df.index))
print(len(df.index.unique()))
```

@singhyun90

**Comment by singhyun90** [comment]
@mr-yoo 

말씀해주신 방법으로 수행했더니, 올바른 결과 나왔습니다!

이슈 종료하셔도 될것같습니다.
도움주셔서 감사합니다 : )
