### ISSUE TITLE
주문 결과 코드가 201로 올 때가 있습니다.

### ISSUE THREAD

**Issue by jihunroh** [sharebook-kr/pyupbit#34]
시장가 매수주문을 `upbit.buy_market_order('KRW-BTC', 6000)`로 냈는데,
계속 `UpbitError`가 출력됩니다만, 주문은 서버에 넘겨져서 거래 체결되더라구요..

request_api.py를 보니
resp.status_code가 200이 아닌 201로 수신되는 상황입니다.
문외한인지라 201도 현 코드와 같이 예외처리로 넘겨야 하는게 맞는지 모르겠습니다.
(거래는 잘 들어가니 괜찮을 것같은데..)

**Comment by brayden-jo** [comment]
그렇네요. 수정하도록 하겠습니다. 감사합니다. 
https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201
