### ISSUE TITLE
get_ohlcv()함수 200개 이상 호출할때 중복열 발생

### ISSUE THREAD

**Issue by singhyun90** [sharebook-kr/pyupbit#54]
@brayden-jo @mr-yoo @jha929 @sharebook-kr 

안녕하세요. 제공해주신 pyupbit 열심히 사용하고 있습니다.
감사합니다.

다름이 아니라,
과거 코인 데이터를 호출할때,
200개 이상 호출하게 되면 반환되는 DataFrame에 중복된 데이터가 발생하게 됩니다.

해결책을 찾아보니 과거 이슈(#30) 답글에 해결책이 있는거같은데,
Master Branche에 아직 반영이 안된것 같아 문의드립니다.

혹시 다른 사유에 의해 반영이 안되는건가요?

**Comment by mr-yoo** [comment]
답변이 조금 늦었습니다. 혹시 최신 버전에서 발생하는 문제일까요? 다음 코드에서는 정상 실행 됩니다. 

```python
df = pyupbit.get_ohlcv('KRW-XRP', interval='minute5', count=1000)
print(len(df.index))
print(len(df.index.unique()))
```
```text
1000
1000
```
문제가 발생했다면 코드도 함께 공유해 주시면 들여다 볼겠습니다.

**Comment by singhyun90** [comment]
@mr-yoo 
안녕하세요 mr-yoo님.

해당 issue의 답변에 대해 바로 답변드리지 못해서 죄송합니다. 그리고 응답해주셔서 감사합니다 : )

제가 파악한 바에의하면,
_**Code를 실행하는 서버의 Timezone에 따라 발생하는 issue(?)인것 같습니다.**_
(코드는 최신버전이며, 위에서 언급해주신 동일코드입니다)

`df = pyupbit.get_ohlcv('KRW-XRP', interval='minute5', count=1000)
print(len(df.index))
print(len(df.index.unique()))`

`1000
568
`

- 혹시 Colab이나 GCP같은곳에서 Test 해도 동일하실까요?
- 저는 colab이나 gcp에서 코드를 수행하는데 아래와 같은 현상이 발생합니다.
- 또한,  #30에서 언급된 이슈와 동일한 이유이며, 동일한 해결책을 사용하면 해결이되는것을 확인이 됬습니다.
           (현재는, #30에서 언급된 해결법을 함수로 직접 따로 생성해서 사용하는 중)

감사합니다 : )

**Comment by mr-yoo** [comment]
문제가 있어 보이네요. 확인해 보겠습니다. 해당 내용은 #30에서 다루도록 하겠습니다.
