### ISSUE TITLE
.get_ohlcv() 함수 minute180 불러오기

### ISSUE THREAD

**Issue by boozesounds** [sharebook-kr/pyupbit#55]
2시간봉이나 3시간봉은 불러오는것이 불가능한가요?

**Comment by mr-yoo** [comment]
업비트 서버에서 제공해주지 않는 경우는 직접 만들어야 합니다.  다음 코드와 같은 형태로 데이터를 정리할 수 있습니다:D
- https://www.tradingbro.co.kr/t/1-3/50
