### ISSUE TITLE
정상 매수 체결되었으나 state가 cancel로 반환되는 이슈

### ISSUE THREAD

**Issue by june5079** [sharebook-kr/pyupbit#56]
안녕하세요. 먼저 좋은 프로그램 만들어 주셔서 감사합니다.

매수 주문 이후에 해당 매수건에 대한 체결 여부를 체크하기 위해
uuid로 get_order 조회시 state 값이 cancel로 표시가 됩니다
(실제 업비트 앱에서는 정상 매수 완료됨)

state 값 외에 다른 값은 다 정상 표기가 되는데요.
혹시 버그일까요...아님 어떤 문제가 있을까요?

**Comment by mr-yoo** [comment]
재현이 될까요? 가능하다면 코드를 공유해주시면 분석을 해볼게요.

**Comment by designmeme** [comment]
지정가가 아닌 시장가로 주문시에 모두 매수/매도가 완료되면 cancel state로 응답이 옵니다. 업비트 문서에 자세한 내용이 적혀있지 않아서 아쉬운 부분이에요
