### ISSUE TITLE
API가 JSON 방식으로 변경된다고 하는데요..

### ISSUE THREAD

**Issue by sis55585** [sharebook-kr/pyupbit#58]
안녕하세요. 
모듈을 사용하고 있는 사용자입니다. 
3월1일자로 JSON 방식으로 변경된다고 합니다. 
혹시 대응하고 계신지요?

**Comment by mr-yoo** [comment]
이제 준비를 해야지요 😂😂
- https://docs.upbit.com/changelog/open-api-%EB%B3%80%EA%B2%BD%EC%82%AC%ED%95%AD-%EC%95%88%EB%82%B4
