### ISSUE TITLE
get_order의 ticker, uuid 없이 조회 불가능한가요?

### ISSUE THREAD

**Issue by kirrkirr** [sharebook-kr/pyupbit#62]
안녕하세요
우선 기능 만들어주셔서 감사합니다.

1. get_order의 ticker, uuid 없이 조회 가능할가요?
2. get_order 에 주문한 시간추가 가능할까요?

**Comment by mr-yoo** [comment]
업비트 API가 제공하지 않는 기능이라서 어려울 것으로 보입니다.
