### ISSUE TITLE
get_ohlcv함수 사용시 일자데이터에 타임존 추가되어 데이터프레임이 반환되는 문제가 있습니다.

### ISSUE THREAD

**Issue by guardhope** [sharebook-kr/pyupbit#84]
1: import pybithumb
2:  
3: df = pybithumb.get_ohlcv("BTC")
4: df['range'] = (df['high'] - df['low']) * 0.5
5: df.to_excel("btc.xlsx")
https://wikidocs.net/21891 여기 나와있는 백테스트 코드를 pyupbit로 바꿔서 해보는데 에러가 발생하여 이후 진행이 안됩니다.
pyupbit 코드 자체 문제로 보여서 여기에 글 남깁니다.

import pyupbit
df = pyupbit.get_ohlcv("KRW-BTC", count=7)
(중간 동일)
df.to_excel("ddd.xlsx")
문제가 되는 부분이 df.to_excel("ddd.xlsx") 이부분이고 ValueError가 발생해서 print(df)로 바꿔서 화면에 출력해보니 아래와 같이 데이터 형식이 일자+타임존인 것이 확인되었습니다.
2022-05-10 09:00:00+09:00  41000000.0  43110000.0  40150000.0  ...  1.000000  1.000000   0.000000

`# timezone will be removed before DataFrame returned`
get_ohlcv 코드 내 주석엔 **타임존 제거 후 데이터프레임이 반환된다고 메모 되어 있으나 데이터프레임에는 일자+타임존으로 저장되는 것으로 보입니다.**

url = get_url_ohlcv(interval=interval)
if to is None:
to = datetime.datetime.now()
elif isinstance(to, str):
to = pd.to_datetime(to).to_pydatetime()
**elif isinstance(to, pd._libs.tslibs.timestamps.Timestamp):**
to = to.to_pydatetime()
quotation_api.py에서 위의 Timestamp가 쓰인 부분이 문제가 되지 않나 싶은데요.
주석과 다르게 타임존 제거 안되고 Timestamp로 반환된 일자+타임존 그대로 dataframe에 저장 되는 것 아닌가요?
타임존 때문에 엑셀뿐만 아니고 get_ohlcv함수 이용한 다른 코드로 테스트 해봐도 동일한 에러가 발생합니다.(코드와 에러기록 제일 밑에 적었습니다.)
코드를 수정해보려고 했는데 다른 부분에서 또 에러가 발생하여 코드 작성하신 분이나 잘 아시는 분이 확인 좀 해주시고 수정하여주셨으면 합니다.

#BTC 최근 200시간의 데이터 불러옴
df = pyupbit.get_ohlcv("KRW-BTC", interval="minute60")

#**시간(ds)**와 종가(y)값만 남김
df = df.reset_index()
df['ds'] = df['index']
df['y'] = df['close']
data = df[['ds','y']]

#학습
model = Prophet()
model.fit(data)

ValueError                                Traceback (most recent call last)
[<ipython-input-16-9afeab43f422>](https://localhost:8080/#) in <module>()
      1 #학습
      2 model = Prophet()
----> 3 model.fit(data)
[/usr/local/lib/python3.7/dist-packages/fbprophet/forecaster.py](https://localhost:8080/#) in setup_dataframe(self, df, initialize_scales)
    263         if df['ds'].dt.tz is not None:
    264             raise ValueError(
--> 265                 'Column ds has timezone specified, which is not supported. '
    266                 'Remove timezone.'
    267             )
ValueError: Column ds has timezone specified, which is not supported. Remove timezone.

**Comment by Eehae** [comment]
ohlcv를 먼저 다른데 (dd) 로 불러서 타임존 지우고 df 에 넣어 주시면 됩니다

df = pybithumb.get_ohlcv("BTC")  이 부분을
아래처럼 바꾸시면 됩니다
dd = pybithumb.get_ohlcv("BTC")
df = dd.tz_localize(None)

**Comment by Eehae** [comment]
df = pyupbit.get_ohlcv("KRW-BTC", interval="minute60") 이부분도 마찬가지로

dd = pyupbit.get_ohlcv("KRW-BTC", interval="minute60")
df = dd.tz_localize(None)

**Comment by brayden-jo** [comment]
timezone 코드를 그냥 제거했습니다.
